### ISSUE TITLE
Bower error

### ISSUE THREAD

**Issue by diefer91** [paulallen87/chaturbate-overlay-app#6]
Hi! I'm getting this error when running locally using the command start-dev.sh: 

```javascript
error:   Error: Request to https://bower.herokuapp.com/packages/web-animations-js failed with 502
    at createError (/Users/die/Desktop/chaturnuevo/node_modules/bower/lib/node_modules/bower-registry-client/lib/util/createError.js:2:15)
    at Request._callback (/Users/die/Desktop/chaturnuevo/node_modules/bower/lib/node_modules/bower-registry-client/lib/lookup.js:107:29)
    at Request.self.callback (/Users/die/Desktop/chaturnuevo/node_modules/bower/lib/node_modules/request/request.js:198:22)
    at Request.emit (events.js:182:13)
    at Request.request.emit (/Users/die/Desktop/chaturnuevo/node_modules/bower/lib/node_modules/request-replay/index.js:69:33)
    at Request.<anonymous> (/Users/die/Desktop/chaturnuevo/node_modules/bower/lib/node_modules/request/request.js:1035:10)
    at Request.emit (events.js:187:15)
    at Request.request.emit (/Users/die/Desktop/chaturnuevo/node_modules/bower/lib/node_modules/request-replay/index.js:69:33)
    at IncomingMessage.<anonymous> (/Users/die/Desktop/chaturnuevo/node_modules/bower/lib/node_modules/request/request.js:962:12)
    at IncomingMessage.emit (events.js:187:15)
error Command failed with exit code 1.
```

**Comment by Screemy** [comment]
you can solve it by create file ".bowerrc" in root app folder with content:

{
  "registry": "https://registry.bower.io"
}


But still app for me not working (without video)
