### ISSUE TITLE
Unhandled 'error' event events.js:174?

### ISSUE THREAD

**Issue by raul7angels** [paulallen87/chaturbate-overlay-app#9]
Hello @paulallen87 

This is a a great project, exactly what I was looking for!
Sadly, I get an error like this when running either dev or production bin/start_dev.sh or bin/start_prod.sh. Any idea what this is all about and how could I resolve it? 
I am running latest Chrome browser, latest Node.js and OSX Sierra.
See the error log below.

Many thanks in advance

Raul

yarn run v1.15.2
$ node index.js
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::8080
    at Server.setupListenHandle [as _listen2] (net.js:1270:14)
    at listenInCluster (net.js:1318:12)
    at Server.listen (net.js:1405:7)
    at Object.<anonymous> (/Apps/OBS/index.js:45:12)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1297:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by paulallen87** [comment]
There is a chance that some other program you have running is already
listening on port 8080.

To find the process ID thats using the port you can try running this in a
terminal: lsof -t -i :8080

Or you can change the ports here:
https://github.com/paulallen87/chaturbate-overlay-app/blob/master/index.js#L45

https://github.com/paulallen87/chaturbate-overlay-app/blob/master/Dockerfile#L78
https://github.com/paulallen87/chaturbate-overlay-app/blob/master/Dockerfile-dev#L35


Of you can try running the docker container and just tell it to map the
internal 8080 port to a different host port.

**Comment by raul7angels** [comment]
Thank you @paulallen87 

You were right, It was a rogue process left open from my previous run attempt, I use killall -9 host to close it.

Now, I got the service running and graphics show up on the browser / OBS however there seems to be some discrepancies on the information scraped from Chaturbate. When did you last test the scraping? Perhaps they have moved some stuff around since 2017 and the code is unable to get correct values? 

As an example: When I load a currently live model username it returns some funny things like "is_boradcasting: false", which should clearly be true, and so on. My gut feeling says that this can cause also a cascade of other problems, like if !is_broadcasting maybe the view count and other elements are being ignored in the code.

What ever the cause the result is that the viewer count is always 0, the room subject is never displayed and chat messages are completely missing. Only elements that seem to be working initially  are the goal completion bar works, goal box on the right seems to show correct data initially, but if there are any changes after the initial service load this data is not being updated.

My goal here is to customise what you have and build animated tip alerts on top of your code.

If  you can help me out on updating the scraping configuration or whatever is causing these discrepancies, that would be very much appreciated :) 

![Screenshot from OBS](https://i.ibb.co/nk3SXsJ/Screen-Shot-2019-04-04-at-6-31-09-pm.png)

**Comment by Bosseylady** [comment]
Is it possible to get in touch directly with PaulAllen87

Many thanks Bosseylady
